### ISSUE TITLE
unable to install lida

### ISSUE THREAD

**Issue by sidhu0708** [microsoft/lida#127]
pip install lida
Collecting lida
  Using cached lida-0.0.14-py3-none-any.whl.metadata (13 kB)
Collecting llmx>=0.0.21a (from lida)
  Using cached llmx-0.0.21a0-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: pydantic in c:\users\panyala.manish\appdata\local\programs\python\python312\lib\site-packages (from lida) (2.8.2)
Requirement already satisfied: uvicorn in c:\users\panyala.manish\appdata\local\programs\python\python312\lib\site-packages (from lida) (0.30.1)
Requirement already satisfied: typer in c:\users\panyala.manish\appdata\local\programs\python\python312\lib\site-packages (from lida) (0.12.3)
Requirement already satisfied: fastapi in c:\users\panyala.manish\appdata\local\programs\python\python312\lib\site-packages (from lida) (0.111.1)
Requirement already satisfied: python-multipart in c:\users\panyala.manish\appdata\local\programs\python\python312\lib\site-packages (from lida) (0.0.9)
Requirement already satisfied: scipy in c:\users\panyala.manish\appdata\local\programs\python\python312\lib\site-packages (from lida) (1.13.1)
Requirement already satisfied: numpy in c:\users\panyala.manish\appdata\local\programs\python\python312\lib\site-packages (from lida) (1.26.4)
Requirement already satisfied: pandas in c:\users\panyala.manish\appdata\local\programs\python\python312\lib\site-packages (from lida) (2.2.2)
Requirement already satisfied: matplotlib in c:\users\panyala.manish\appdata\local\programs\python\python312\lib\site-packages (from lida) (3.9.0)
Collecting altair (from lida)
  Using cached altair-5.3.0-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: seaborn in c:\users\panyala.manish\appdata\local\programs\python\python312\lib\site-packages (from lida) (0.13.2)
Requirement already satisfied: plotly in c:\users\panyala.manish\appdata\local\programs\python\python312\lib\site-packages (from lida) (5.22.0)
Collecting plotnine (from lida)
  Using cached plotnine-0.13.6-py3-none-any.whl.metadata (8.9 kB)
Collecting statsmodels (from lida)
  Using cached statsmodels-0.14.2-cp312-cp312-win_amd64.whl.metadata (9.5 kB)
Requirement already satisfied: networkx in c:\users\panyala.manish\appdata\local\programs\python\python312\lib\site-packages (from lida) (3.3)
Collecting geopandas (from lida)
  Using cached geopandas-1.0.1-py3-none-any.whl.metadata (2.2 kB)
Collecting matplotlib-venn (from lida)
  Using cached matplotlib-venn-1.0.0.tar.gz (34 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\panyala.manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\panyala.manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\panyala.manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel      
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\panyala.manish\AppData\Local\Temp\pip-build-env-priidkbx\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\panyala.manish\AppData\Local\Temp\pip-build-env-priidkbx\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\panyala.manish\AppData\Local\Temp\pip-build-env-priidkbx\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 14, in <module>
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Comment by phanindrakumarcs** [comment]
how do you resolve this. I am facing the same issue in mac environment ?
