### ISSUE TITLE
Lida Code is not working for Azure OpenAI Credentials

### ISSUE THREAD

**Issue by ShaikSohail263** [microsoft/lida#129]
I'm trying to run LIDA for generating visualizations, For multiple times I tried running but i'm facing this error. Can Someone Please help me out with this???

from lida import Manager, TextGenerationConfig , llm 
import OS

text_gen = llm(provider="openai",
                api_type="azure", 
                azure_endpoint= os.getenv["Azure_Base"], 
                api_key=os.getenv["API_KEY"],    
                api_version="2021-11-15-preview"
                ) 

lida = Manager(text_gen=text_gen)

textgen_config = TextGenerationConfig(n=1, temperature=0.5, model="gpt-3.5-turbo-16k", use_cache=True)

summary = lida.summarize("filename.csv", summary_method="default", textgen_config=textgen_config)  

user_query = "What is the average price of cars by type?"
textgen_config = TextGenerationConfig(n=1, temperature=0.2, use_cache=True)
charts = lida.visualize(summary=summary, goal=user_query, textgen_config=textgen_config)  
charts[0]

For this code I'm getting this error

**"openai.NotFoundError: Error code: 404 - {'error': {'code': 'DeploymentNotFound', 'message': 'The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.'}"**

even if I try after 5 mins I'm facing the same issue

Note : I'm using all the recent versions of the libraries
<img width="698" alt="error" src="https://github.com/user-attachments/assets/35f5e95a-4cdd-49c8-93f8-09767431c807">

**Comment by aiplayer93** [comment]
Hello @ShaikSohail263 @victordibia, I am having the same issue with my Azure Open AI deployments not being identified by LIDA.I followed the same code as  @ShaikSohail263  and I had the following error too:

openai.NotFoundError: Error code: 404 - {'error': {'code': 'DeploymentNotFound', 'message': 'The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.'}}

Thanks for the help
