### ISSUE TITLE
Large dataset summary exceeds context size?

### ISSUE THREAD

**Issue by 0xaaiden** [microsoft/lida#16]
Uploaded a fairly large datasets (> 40 columns) and seems like the summary and response size exceeded the maximum context size.

Would it be possible to compress the summary size or let the users choose which columns are relevant to generate charts?

![image](https://github.com/microsoft/lida/assets/30964272/d346fe00-6108-4b15-b3e1-87cfaaa9e419)

**Comment by victordibia** [comment]
Yes! This is a great idea, and important too! 
Will start work on a fix and post updates here!
