### ISSUE TITLE
Mac installation error: geos_c.h not found

### ISSUE THREAD

**Issue by ajduberstein** [microsoft/lida#19]
I suspect a number of Mac users will run into a GEOS issue on `pip install lida`

```bash
      src/_geoslib.c:751:10: fatal error: 'geos_c.h' file not found
      #include "geos_c.h"
               ^~~~~~~~~~
      1 warning and 1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  ERROR: Failed building wheel for basemap
```

This fixes the problem in my case:

```bash
brew install geos
export CPPFLAGS="-I/opt/homebrew/include"
export LDFLAGS="-L/opt/homebrew/lib"
pip install basemap
pip install lida
```

It may be helpful to include some mention of this in the docs or make the inclusion of `basemap` optional.

### Context

Running Mac OS 13.2.1, Python 3.10.5

**Comment by victordibia** [comment]
Thanks for sharing this. 
I'll try to reproduce. 
In the mean time, basemap is not a required dependency, so you can modify `[pyproject.toml](https://github.com/microsoft/lida/blob/main/pyproject.toml)` to remove it and then install from source `pip install -e .` in the project root.
