### ISSUE TITLE
pip install err 

### ISSUE THREAD

**Issue by xk503775229** [microsoft/lida#31]
Thank you very much for open-sourcing this tool. I have encountered some problems. Could you please take a look and see how to solve them?

ERROR: Could not find a version that satisfies the requirement llmx (from lida)
ERROR: No matching distribution found for llmx

brach -main
command pip install .

**Comment by victordibia** [comment]
Can you share moree on your environment (e.g. mac, python version .. note that lida requires pythong 3.9 and above) and the full error message?

**Comment by xk503775229** [comment]
> Can you share moree on your environment (e.g. mac, python version .. note that **lida requires pythong 3.9** and above) and the full error message?
