### ISSUE TITLE
 Error: 'DataFrame' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by piecesyoyo** [microsoft/lida#34]
File [c:\ProgramData\anaconda3\lib\site-packages\lida\components\manager.py:73](file:///C:/ProgramData/anaconda3/lib/site-packages/lida/components/manager.py:73), in Manager.summarize(self, data, file_name, n_samples, summary_method, textgen_config)
     71 self.data = data
     72 # self.data = data
---> 73 return self.summarizer.summarize(
     74     data=self.data, text_gen=self.text_gen, file_name=file_name, n_samples=n_samples,
     75     summary_method=summary_method, textgen_config=textgen_config)

File [c:\ProgramData\anaconda3\lib\site-packages\lida\components\summarizer.py:127](file:///C:/ProgramData/anaconda3/lib/site-packages/lida/components/summarizer.py:127), in Summarizer.summarize(self, data, text_gen, file_name, n_samples, textgen_config, summary_method)
    125     file_name = data.split("/")[-1]
    126     data = read_dataframe(data)
--> 127 data_properties = self.get_column_properties(data, n_samples)
    129 # default single stage summary construction
    130 base_summary = {
    131     "name": file_name,
    132     "file_name": file_name,
    133     "dataset_description": "",
    134     "fields": data_properties,
    135 }

File [c:\ProgramData\anaconda3\lib\site-packages\lida\components\summarizer.py:38](file:///C:/ProgramData/anaconda3/lib/site-packages/lida/components/summarizer.py:38), in Summarizer.get_column_properties(self, df, n_samples)
     36 properties_list = []
     37 for column in df.columns:
---> 38     dtype = df[column].dtype
     39     properties = {}
     40     if dtype in [int, float, complex]:

File [c:\ProgramData\anaconda3\lib\site-packages\pandas\core\generic.py:6202](file:///C:/ProgramData/anaconda3/lib/site-packages/pandas/core/generic.py:6202), in NDFrame.__getattr__(self, name)
   6195 if (
   6196     name not in self._internal_names_set
   6197     and name not in self._metadata
   6198     and name not in self._accessors
   6199     and self._info_axis._can_hold_identifiers_and_holds_name(name)
   6200 ):
   6201     return self[name]
-> 6202 return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'dtype'

**Comment by victordibia** [comment]
Hi,

If you can provide more information on the content of the data and the code that triggers this, that would be helpful.
