### ISSUE TITLE
Plotly issue in visualize

### ISSUE THREAD

**Issue by C-Adames** [microsoft/lida#36]
Hi, 

Im having issues when using 'plotly' as library.

Example :

i = 0
library = 'plotly'
textgen_config = TextGenerationConfig(n=1, temperature=0.2, use_cache=True)
charts = lida.visualize(summary=summary, goal=goals[i], textgen_config=textgen_config, library=library) 
plot_raster(charts[0].raster) 

Returns:

ValueError: Unsupported library. Choose from 'matplotlib', 'seaborn', 'plotly', 'bokeh', 'ggplot', 'altair'.

**Comment by victordibia** [comment]
@trojrobert, any chance you can contribute a fix to this?

**Comment by trojrobert** [comment]
Yes I will check it out

**Comment by Alfred-Onuada** [comment]
Hi @victordibia and @trojrobert I just opened a PR to address this issue, please have a look

**Comment by victordibia** [comment]
Closing this as it has been addressed by PR #44
