### ISSUE TITLE
edited_charts[0].raster  为空

### ISSUE THREAD

**Issue by houjibofa2050** [microsoft/lida#38]
colab environment

the code show as below

code show as below
`from lida import Manager, TextGenerationConfig, llm
    from lida.utils import plot_raster
    from lida import Manager

    lida = Manager()
    summary = lida.summarize("../data/cars.csv")  # generate data summary
    print("summary:", summary)
    # 将字典转换为JSON字符串
    import json

    summary_string = json.dumps(summary)

    # 打印JSON字符串
    print(summary_string)

    goals = lida.goals(summary, n=5)
    print("goals", goals)

    # 生成可视化代码
    charts = lida.visualize(summary=summary, goal=goals[0], library="matplotlib")
    print(charts)
    code = charts[0].code
    # 绘制图
    # 本质是对图片进行解码，展示图片
    plot_raster(charts[0].raster)

    library = "seaborn"
    # code = charts[0].code
    textgen_config = TextGenerationConfig(n=1, temperature=0, use_cache=True)
    instructions = ["zoom in 50%", "make the chart height and width equal", "change the color of the chart to red",
                    "translate the chart to spanish"]
    edited_charts = lida.edit(code=code, summary=summary, instructions=instructions, library=library,
                              textgen_config=textgen_config)
    plot_raster(edited_charts[0].raster)
`
The error is reported as follows
![lida错误截图](https://github.com/microsoft/lida/assets/19608744/c7c4b8cb-5916-4743-a454-7f5d12aceb0d)

**Comment by trojrobert** [comment]
@houjibofa2050 Before calling lida.edit, please can you show me the output of code and the output of plot_raster
