### ISSUE TITLE
LIDA rename columns

### ISSUE THREAD

**Issue by trojrobert** [microsoft/lida#42]
![Screenshot from 2023-09-20 08-33-11](https://github.com/microsoft/lida/assets/28733978/8f84c21d-5bb8-4337-8c8d-30796402a775)

LIDA columns replace special characters with _

**Comment by victordibia** [comment]
Can you explain the exact issue? E.g., are you saying that replacing column names with special characters is a problem? If so, what is the use case, and how does this impact the developer workflow?

**Comment by trojrobert** [comment]
I was building an app where I wanted to do more with the column names. For instance, I wanted to show number of nan and manually and more details about the data

**Comment by victordibia** [comment]
Thanks for the clarification. It seems to me that your app should keep track of the dataset and all other processing needed without relying on LIDA's representation of the data by the Manager (`.data`).  You can also keep track of both name lists and use that information as needed. Note that the column index will not change, but the title may.

In general, the renaming is done (and required) for two high level reasons: 
- Data with special characters in column names can lead to serialization errors (e.g., data not being saved or loaded correctly in ) 
- Having clear column names as single variables (e.g., removing space etc) makes it easier for LLMs to reference those columsn and ground the generated code using those column names. Without this, the LLM is more likely to hallucinate incorrect names. 


What do you think?

**Comment by trojrobert** [comment]
I understand why the column renaming is importance. Serialization error can be a big problem.
 Maybe we can add a note in the code  or in the summary that let the user have an idea of some things that changed and few information about the summary
