### ISSUE TITLE
Access to the code generated to plot

### ISSUE THREAD

**Issue by teraktor2006** [microsoft/lida#59]
Hi, Is there any way to get access to the code that lida generate and use to plot?

**Comment by victordibia** [comment]
Can you share the code you have right now? 


In general,

```python 


from lida import Manager, llm

lida = Manager(text_gen = llm("openai")) # palm, cohere ..
summary = lida.summarize("data/cars.csv")
goals = lida.goals(summary, n=2) # exploratory data analysis
charts = lida.visualize(summary=summary, goal=goals[0]) # exploratory data analysis 

```

In the snippet above, charts is an array of objects [ChartExecutorResponse](https://github.com/microsoft/lida/blob/97cf614317fdf3fac28de75ae0f51d4599cb2f92/lida/datamodel.py#L189C7-L189C28) which has a code field. 

```python
charts[0].code
```

**Comment by teraktor2006** [comment]
Thanks.
I am using this demo:
https://github.com/AIAnytime/LIDA-Demo-Streamlit-App/blob/main/app.py

Another problem that I am facing for some queries is that the charts is empty list []. But interestingly, once it happens it shows the code as log and that code is actually working! I was wondering is this a bug? The problem is that if list is empty then I cannot access that code either with charts[0].code
