### ISSUE TITLE
Error processing csv

### ISSUE THREAD

**Issue by vadi2** [microsoft/lida#61]
Hi!

Uploading the following .csv is giving a "An error occurred. Please try again later." message. It looks like it's struggling with the CSV, the error message is:

> Error processing file: Error tokenizing data. C error: Expected 4 fields in line 257, saw 5

The last cell has unescapes quotes in it, which is probably the issue.

[results.csv](https://github.com/microsoft/lida/files/13257363/results.csv)

**Comment by victordibia** [comment]
Can you print out the content of the console? Were any errors logged?

**Comment by jimiopex** [comment]
Facing the similar error when I use hugging face

INFO:     Uvicorn running on http://127.0.0.1:8081 (Press CTRL+C to quit)
INFO:     Started reloader process [79382] using WatchFiles
INFO:     Started server process [79386]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:65484 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:65484 - "GET /images/videoscreen.png HTTP/1.1" 200 OK
INFO:     127.0.0.1:65485 - "GET /files/lidamodules.jpg HTTP/1.1" 200 OK
INFO:     127.0.0.1:65487 - "GET /app-80dcacffbc4d71399cc7.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:65486 - "GET /files/infographics_small.jpg HTTP/1.1" 200 OK
INFO:     127.0.0.1:65488 - "GET /framework-adcf09f5896f386aa38b.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:65490 - "GET /webpack-runtime-8958b079d5c4b6876c66.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:65486 - "GET /page-data/app-data.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:65485 - "GET /page-data/index/page-data.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:65484 - "GET /webpack-runtime-8958b079d5c4b6876c66.js.map HTTP/1.1" 200 OK
INFO:     127.0.0.1:65488 - "GET /framework-adcf09f5896f386aa38b.js.map HTTP/1.1" 200 OK
INFO:     127.0.0.1:65490 - "GET /app-80dcacffbc4d71399cc7.js.map HTTP/1.1" 200 OK
INFO:     127.0.0.1:65487 - "GET /component---src-pages-index-tsx-36a4bd360cacad51120f.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:65485 - "GET /81e257386408544e35976acc2a4075b730ed48a4-326068d326429305ec9e.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:65486 - "GET /21614df092a0a42959abd49fa5ffec5702fa9463-ea1bf954f60f23d1e6a7.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:65487 - "GET /page-data/sq/d/1865044719.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:65487 - "GET /component---src-pages-index-tsx-36a4bd360cacad51120f.js.map HTTP/1.1" 200 OK
INFO:     127.0.0.1:65486 - "GET /21614df092a0a42959abd49fa5ffec5702fa9463-ea1bf954f60f23d1e6a7.js.map HTTP/1.1" 200 OK
INFO:     127.0.0.1:65485 - "GET /81e257386408544e35976acc2a4075b730ed48a4-326068d326429305ec9e.js.map HTTP/1.1" 200 OK
INFO:     127.0.0.1:65486 - "GET /favicon-32x32.png?v=ec9820d5698bdcb03284cb1dd7c5625d HTTP/1.1" 200 OK
INFO:     127.0.0.1:65506 - "GET /manifest.webmanifest HTTP/1.1" 200 OK
INFO:     127.0.0.1:65485 - "GET /page-data/demo/page-data.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:65485 - "GET /component---src-pages-demo-tsx-54fd6da10fa870d8d843.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:65485 - "GET /component---src-pages-demo-tsx-54fd6da10fa870d8d843.js.map HTTP/1.1" 200 OK
INFO:     127.0.0.1:65485 - "GET /models HTTP/1.1" 200 OK
Error processing file: Error tokenizing data. C error: Expected 1 fields in line 10, saw 3
